config/routes.rb
Rails.application.routes.draw do
  resources :tables

  devise_for :users, :skip => :registrations

  resources :parties
  resources :groups
  resources :guests
  resources :users

  get '/save-the-date-a' => 'parties#save_the_date_a'
  get '/save-the-date-b' => 'parties#save_the_date_b'
  get '/save-the-date-special' => 'parties#save_the_date_special'
  get '/reminder' => 'parties#send_reminder_email'
  get '/outer_labels' => 'parties#create_outer_labels'
  get '/place_cards' => 'parties#create_place_card_labels'
  get '/seating_chart' => 'parties#get_seating_chart_data'
  get '/rsvp_details' => 'parties#get_party_details'
  get '/tags' => 'parties#tags'
  get '/rsvp_cards' => 'parties#rsvp_cards'
  get '/detail' => 'parties#detail_list'

  root 'home#index'

  get '/our_story' => 'home#our_story'
  get '/wedding' => 'home#wedding'
  get '/reception' => 'home#reception'
  get '/registry' => 'home#registry'
  get '/wedding_party' => 'home#wedding_party'
  get '/guest_info' => 'home#guest_info'
  get '/rsvp' => 'home#rsvp'
  get '/pictures' => 'home#photos'

  get '/rsvp/search' => 'home#search'
  get '/address_update' => 'home#user_update'
  get '/update_party' => 'home#update_party'
  get '/party_guests/:id' => 'home#get_guests'
  get '/get_parties/:id' => 'home#get_parties'

  resources :photos

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    render :layout => 'home'
  end

  def wedding
    render :layout => 'application'
  end

  def our_story
    render :layout => 'application'
  end

  def reception
    render :layout => 'application'
  end

  def wedding_party
    render :layout => 'application'
  end

  def guest_info
    render :layout => 'application'
  end

  def registry
    render :layout => 'application'
  end

  def photos
    @photos = {}
    @photos[:engagement] = Photo.all.where(:category => 'Engagement Photos').reorder(:avatar_file_name)
    @photos[:party] = Photo.all.where(:category => 'Engagement Party').reorder(:avatar_file_name)
    @photos[:shower] = Photo.all.where(:category => 'Wedding Shower').reorder(:avatar_file_name)
    render :layout => 'application'
  end

  def user_update
    if params[:t]
      party = PartyEncoder.decode(params[:t])
      @party = Party.find(/[0-9]+/.match(party).to_s)
      render :layout => 'application'
    else
      redirect_to root_path
    end
  end

  def update_party
    party_params = params.permit(:name, :email, :address, :city, :state, :postal_code, :country)
    party_params[:confirmed] = true
    @party = Party.find(params[:id])

    if @party.update(party_params)
      flash.keep[:notice] = 'Your details have been successfully updated. Keep a look out for your invitation!'
      redirect_to root_path
    else
      respond_to do |format|
        format.html { redirect_to user_update_path, notice: 'Something went wrong' }
        format.json { head :no_content }
      end
    end
  end

  def get_guests
    guests = Party.find(params[:id]).guests
    rehearsal = false
    brunch = false

    guests.each do |g|
      if GroupsGuests.where(group_id: 6, guest_id: g.id).present?
        rehearsal = true
      end

      if GroupsGuests.where(group_id: 7, guest_id: g.id).present?
        brunch = true
      end
    end

    render json: {:guests => guests, :rehearsal => rehearsal, :brunch => brunch}
  end

  def get_parties
    parties = nil

    if params[:id] == 'JFK2015'
      parties = Party.joins(:guests).select(:first_name, :last_name, :id, :suffix).where('(rsvp != ? OR rsvp IS NULL) AND a_b_list = ?', true, 'A')
        .map{|p| { :label => "#{p.first_name} #{p.last_name} #{p.suffix}", :party_id => p.id} }
    end

    render json: {:parties => parties}
  end

  def rsvp
    @id_code = params[:code]
    render :layout => 'application'
  end

  def search
    code = params[:id_code].upcase
    party_size = params[:party]
    party_size_rehearsal = params[:party_rehearsal]
    party_size_brunch = params[:party_brunch]
    rsvp = params[:rsvp]
    rsvp_rehearsal = params[:rsvp_rehearsal]
    rsvp_brunch = params[:rsvp_brunch]
    party_id = params[:rsvp_party]

    party = Party.find(party_id)

    respond_to do |format|
      if code != 'JFK2015'
        flash[:error] = 'Invalid Token'
        format.html { redirect_to rsvp_url, error: 'Invalid Token' }
        format.json { head :no_content }
      else
        update_guests(party) if rsvp == '1'
        party.rsvp = rsvp == '1' ? true : false

        if rsvp_rehearsal == '1'
          party.rsvp_dinner = true
          party.size_rehearsal = party_size_rehearsal.present? ? party_size_rehearsal : party_size
        elsif party_size_rehearsal.present? && party_size_rehearsal != '0'
          party.rsvp_dinner = true
          party.size_rehearsal = party_size_rehearsal
        elsif rsvp_rehearsal == '0' && party_size_rehearsal == '0'
          party.rsvp_dinner = false
        end

        if rsvp_brunch == '1'
          party.rsvp_brunch = true
          party.size_brunch = party_size_brunch.present? ? party_size_brunch : party_size
        elsif party_size_brunch.present? && party_size_brunch != '0'
          party.rsvp_brunch = true
          party.size_brunch = party_size_brunch
        elsif rsvp_brunch == '0' && party_size_brunch == '0'
          party.rsvp_brunch = false
        end

        party.size = party_size
        party.save!

        party.reload
        Emailer.send_notification_of_rsvp_email(party).deliver

        message_start = 'Thank you for your RSVP!'
        message = rsvp == '1' ? "#{message_start} We are looking forward to seeing you at the wedding!" : "#{message_start} Sorry you are unable to attend the wedding."

        format.html { redirect_to root_url, notice: message }
        format.json { head :no_content }
      end
    end
  end

  def update_guests(party)
    guests = party.guests
    idx = 0
    params[:meal].each do |m|
      first_name = nil
      last_name = nil

      if params['guest'] && params['guest'][idx.to_s]
        first_name = params['guest'][idx.to_s].scan(/.*\s/)[0]

        if first_name == nil
          first_name = params['guest'][idx.to_s].strip
        else
          first_name.strip!
          last_name = params['guest'][idx.to_s].scan(/\s.*/)[0].strip
        end
      end

      if guests[idx]
        guests[idx].meal_option = m[1]
        guests[idx].first_name = first_name if first_name.present?
        guests[idx].last_name = last_name if last_name.present?
        guests[idx].save!
      else
        Guest.create!(
            :first_name => first_name ? first_name : 'Guest',
            :last_name => last_name || first_name ? last_name : (idx + 1).to_s,
            :party => party,
            :meal_option => m[1]
        )
      end
      idx = idx + 1
    end

    while guests[idx].present?
      if guests[idx].first_name && guests[idx].first_name.include?('Guest')
        guests[idx].destroy
      end
      idx = idx + 1
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_engagement_photos.html.erb
<div class="tab-pane active" id="engagement">
  <h1>Engagement Photos</h1>
  <div class="photos">
    <% idx = 0 %>
    <% @photos[:engagement].each do |p| %>
        <%= image_tag p.avatar.url(:medium), :class => 'lazy', :id => "engagement-#{idx}" %>
        <% idx = idx + 1 %>
    <% end %>
  </div>
</div>

app/views/home/_footer.html.erb
<div class="footer">
  <span class="heart left">&hearts;</span>
  <span class="heart right">&hearts;</span>
  <hr style="float: left;">
  <hr style="float: right;">
</div>

app/views/home/_wedding_shower_photos.html.erb
<div class="tab-pane" id="shower">
  <h1>Wedding Shower</h1>
  <div class="photos">
    <% idx = 0 %>
    <% @photos[:shower].each do |p| %>
        <%= image_tag p.avatar.url(:medium), :class => 'lazy', :id => "shower-#{idx}" %>
        <% idx = idx + 1 %>
    <% end %>
  </div>
</div>

app/views/home/about_us.html.erb
<h1>OurStory#index</h1>
<p>Find me in app/views/our_story/index.html.erb</p>

app/views/home/guest_info.html.erb
<div class="info-box">
  <header>Guest Information</header>

  <section class="row">

    <div class="col-sm-3 hidden-xs" id="myScrollspy">
      <ul class="nav nav-tabs nav-stacked" data-spy="affix" data-offset-top="60" data-offset-bottom="200">
        <li><a href="#venue">Venues</a></li>
        <li><a href="#locations">Travel</a></li>
        <li><a href="#accommodation">Accommodation</a></li>
      </ul>
    </div>

    <div class="col-sm-9">
      <div class="panel-group" id="accordion">
        <%= render 'home/guest_info/venue_info' %>
        <%= render 'home/guest_info/travel_info' %>
        <%= render 'home/guest_info/accommodation_info' %>
      </div>
    </div>
  </section>


  <%= render 'footer' %>
</div>

<script type="text/javascript"
        src="https://maps.googleapis.com/maps/api/js?key=<%=ENV['GOOGLE_API_KEY'] %>">
</script>
<script type="text/javascript" src="http://google-maps-utility-library-v3.googlecode.com/svn/trunk/markerwithlabel/src/markerwithlabel.js"></script>

<script type="text/javascript">
    google.maps.event.addDomListener(window, 'load', initialize);
</script>

app/views/home/index.html.erb
<% flash.each do |name, msg| %>
    <% alert_class = name == 'notice' ? 'alert-success' : 'alert-danger' %>
    <div class='alert <%= alert_class %> alert-dismissible visible-xs visible-sm' id="notice" role="alert">
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
      </button>
      <%= msg %>
    </div>
<% end %>
<div class="col-md-3 countdown">
  <div class="box">
    <div>
      <p class="heart">&hearts;</p>

      <p class="keep">Keep</p>

      <p class="calm">Calm</p>

      <p class="wedding-countdown">Wedding Countdown<br><br><b style='font-size: 28px'>#JFK2015</b></p>
    </div>
    <table id="table" border="0">
      <tr>
        <td align="center" colspan="4">
          <div class="numbers" id="count2" style="padding: 10px; "></div>
        </td>
      </tr>
      <tr id="spacer1">
        <td align="center">
          <div class="numbers" id="dday"></div>
        </td>
        <td align="center">
          <div class="numbers" id="dhour"></div>
        </td>
        <td align="center">
          <div class="numbers" id="dmin"></div>
        </td>
        <td align="center">
          <div class="numbers" id="dsec"></div>
        </td>
      </tr>
      <tr id="spacer2">
        <td align="center">
          <div class="title" id="days">Days</div>
        </td>
        <td align="center">
          <div class="title" id="hours">Hours</div>
        </td>
        <td align="center">
          <div class="title" id="minutes">Minutes</div>
        </td>
        <td align="center">
          <div class="title" id="seconds">Seconds</div>
        </td>
      </tr>
    </table>

    <div>
      <a href="http://ate.so/?DMbSKdO" title="Add to Calendar" class="addthisevent">
        Add to Calendar
        <span class="_start">07-25-2015 00:00:00</span>
        <span class="_end">07-25-2015 00:00:00</span>
        <span class="_zonecode">11</span>
        <span class="_summary">Jessica & Fred's Wedding</span>
        <span class="_location">Huntsville, AL</span>
        <span class="_organizer">Jessica & Fred</span>
        <span class="_organizer_email">jbrazelton@knology.net</span>
        <span class="_all_day_event">true</span>
        <span class="_date_format">DD/MM/YYYY</span>
      </a>
    </div>
  </div>

  <br>
</div>

<div class="col-md-5 col-md-offset-4">
  <div class="title">
    <p class="names">Jessica &amp; Fred </p>

    <p class="info">
      July 25, 2015<br>
      Huntsville, Alabama
    </p>
  </div>
  <br>
  <br>

  <div class="welcome">
    <p>Hi Friends &amp; Family!</p>

    <p>
      Welcome to our website! Thank you for visiting. We are very excited to be getting married this year and we hope
      you can join us for our wedding. Our destination is Huntsville, Alabama, USA for the weekend of July 25, 2015.
      As we work out the details we will keep you posted.
    </p>
  </div>
</div>

app/views/home/our_story.html.erb
<div class="info-box">
  <header>Our Story</header>

  <section class="our-story">
    <div class="vertical-line"></div>

    <span class="heart-divider left">
      <span class="heart">&hearts;</span>
      <span class="title">Frederick Kazembe</span>
    </span>
    <%= render 'home/our_story/fred' %>

    <span class="heart-divider right">
      <span class="title">Jessica Lynn Brazelton</span>
      <span class="heart">&hearts;</span>
    </span>
    <%= render 'home/our_story/jessica' %>

    <span class="heart-divider left">
      <span class="heart">&hearts;</span>
      <span class="title">How We Met</span>
    </span>
    <%= render 'home/our_story/meeting' %>

    <span class="heart-divider right">
        <span class="title">The Engagement</span>
        <span class="heart">&hearts;</span>
    </span>
    <%= render 'home/our_story/engagement' %>

  </section>

  <%= render 'footer' %>
</div>

app/views/home/photos.html.erb
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">
          <span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h3 class="modal-title" id="myModalLabel"></h3>
      </div>
      <div class="modal-body">

        <div id="all-photos" class="carousel slide" data-ride="carousel">

          <!-- Wrapper for slides -->
          <div class="carousel-inner">
            <% @photos.each do |items| %>
                <% idx = 0 %>
                <% items[1].each do |p| %>
                    <div class="item" id="<%= "#{items[0]}-#{idx}" %>">
                      <%= image_tag p.avatar.url %>
                    </div>
                    <% idx = idx + 1 %>
                <% end %>
            <% end %>
          </div>

          <!-- Controls -->
          <a class="left carousel-control" href="#all-photos" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left"></span>
          </a>
          <a class="right carousel-control" href="#all-photos" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right"></span>
          </a>
        </div>

      </div>
    </div>
  </div>
</div>

<div class="info-box">
  <header>Photos</header>

  <section class="images">

    <ul class="nav nav-pills nav-justified">
      <li class="active">
        <a href="#engagement" role="tab" data-toggle="tab" class="btn btn-default">
          Engagement Photos
        </a>
      </li>
      <li>
        <a href="#engagement-party" role="tab" data-toggle="tab" class="btn btn-default">
          Engagement Party
        </a>
      </li>
      <li>
        <a href="#shower" role="tab" data-toggle="tab" class="btn btn-default">
          Wedding Shower
        </a>
      </li>
    </ul>

    <div class="clearfix"></div>

    <div class="tab-content">
      <%= render 'engagement_photos' %>
      <%= render 'engagement_party_photos' %>
      <%= render 'wedding_shower_photos' %>
      <%= render 'wedding_ceremony_photos' %>
      <%= render 'wedding_reception_photos' %>
    </div>
  </section>

  <!-- <br><br>
  <iframe width="100%" height="500px" frameborder="0"
          src="http://trycapsule.com/widgets/photos?access_token=d652a8d28d6461t8"></iframe> -->
</div>

<%= javascript_include_tag 'jquery.lazyload.min' %>
<%= javascript_include_tag 'bootstrap.min' %>
<%= javascript_include_tag 'photos.js' %>

<script>
    setupPhotoDisplay(<%= @photos[:engagement].size %>, <%= @photos[:party].size %>, <%= @photos[:shower].size %>);
</script>

app/views/home/reception.html.erb
<% date = '2015-05-01'.to_date %>

<div class="info-box venue">
  <header>The Reception</header>

  <% if Date.today >= date || user_signed_in? %>
      <div>
        <%= image_tag 'ledges.jpg' %>
        <h1>The Ledges</h1>

        <h3>32 Castle Down Dr, Huntsville, AL 35802</h3>
        <section>
          The Clubhouse is an architectural masterpiece perched on the westernmost point of Huntsville Mountain,
          overlooking
          southeast Huntsville. An English Tudor Manor house measuring over 36,000 square feet, is situated between the
          No.
          1
          and No. 18 fairways. The clubhouse encompasses a grand hall, private men's and ladie's lounges, bars, two
          dining
          rooms, a ballroom, private meeting rooms, and a well-appointed Pro Shop. The upper and lower levels have
          verandas
          for members to enjoy outside dining and sunsets overlooking the formal gardens. <br><br>

          <strong>The reception will be held at the Ledges of Huntsville immediately after the wedding ceremony. Cocktails, dinner and
            dancing
            to follow. Come and celebrate with us!</strong>
        </section>

        <div class="link"><a class="view" href="//www.theledges.com/" target="_blank"></a></div>

        <%= render 'footer' %>
      </div>
  <% else %>
      <%= render 'common/to_be_announced' %>
  <% end %>
</div>

app/views/home/registry.html.erb
<div class="info-box">
  <header>Registry</header>

  <section>
    <strong>
      Everything we put on the registry are things we would love to have to spruce up the house, but honestly,
      the most important gift you can bring us is your presence at our celebration. We are excited to
      spend our special day with you and feel very blessed to have you in our lives!
    </strong>
  </section>

  <br>
  <div class="hidden-lg">
    <a href="http://www.myregistry.com/public/jessicaandfred"><%= image_tag 'registry.jpg' %></a>
  </div>

  <div class="visible-lg">
    <div class="registry-list">
      <script id='script_myregistry_giftlist_iframe' type='text/javascript'
              src='http://www.myregistry.com/Visitors/GiftList/iFrames/EmbedRegistry.ashx?r=rN2j2P4nhNAj2OXQPNijBQ2'>

      </script>
    </div>
  </div>

  <!--<iframe width="100%" height="500px" src="http://www.myregistry.com/public/jessicaandfred"></iframe>-->
</div>

app/views/home/rsvp.html.erb
<%= javascript_include_tag 'rsvp.js' %>

<div class="info-box rsvp">
    <header>RSVP</header>

    <section>
        Use the identification code given in your invitation to RSVP.
    </section>

    <%= form_tag(rsvp_search_path, method: 'get', :class => 'form-horizontal', :role => 'form') do %>
    <div class="form-group">
        <%= label_tag :id_code, 'Identification Code', :class => 'control-label col-sm-4' %>
        <div class="col-sm-6">
            <%= text_field_tag :id_code, '', :class => 'form-control all-caps', :placeholder => 'e.g. A4RTC9', :required => :required, :autocomplete => 'off', :value => @id_code %>
        </div>
    </div>

    <div class="form-group hidden rsvp_guest">
        <%= label_tag :rsvp_party_input, 'Who are you RSVPing for?', :class => 'control-label col-sm-4' %>
        <div class="col-sm-6">
            <%= text_field_tag :rsvp_party_input, '', :class => 'form-control', :required => :required, :placeholder => 'Your Name' %>
        </div>
    </div>

    <div class="form-group rsvp_party">
        <div class="col-sm-10">
            <%= select_tag :rsvp_party, options_from_collection_for_select(party_options, "id", "name"), :include_blank => true, :class => 'form-control hidden', :required => :required, :id => :rsvp_party %>
            <h3 class='hidden rsvp-party-label'></h3>
        </div>
    </div>

    <div id="party-size" class="form-group">
        <%= label_tag :party, 'Total in your party?', :class => 'control-label col-sm-4' %>
        <div class="col-sm-3">
            <%= text_field_tag :party, '', :class => 'form-control', :required => :required, :type => 'number', :min => 1 %>
        </div>
    </div>

    <div class="form-group">
        <%= label_tag :attending, 'Are you attending?', :class => 'control-label col-sm-4' %>
        <div class="col-sm-3">
            <label class="radio-inline">
                <input type="radio" name="rsvp" id="yes" required="required" value='1'> Yes
            </label>
            <label class="radio-inline">
                <input type="radio" name="rsvp" id="no" value='0'> No
            </label>
        </div>
    </div>

    <div class="form-group rehearsal">
        <%= label_tag :rehearsal, 'Will <i>everyone</i> in your party be attending the <strong>Rehearsal dinner</strong> on <strong>Friday, July 24</strong>?'.html_safe, :class => 'control-label col-sm-4' %>
        <div class="col-sm-3">
            <label class="radio-inline">
                <input type="radio" name="rsvp_rehearsal" id="yes-rehearsal" value='1'> Yes
            </label>
            <label class="radio-inline">
                <input type="radio" name="rsvp_rehearsal" id="no-rehearsal" value='0'> No
            </label>
        </div>
    </div>
    <div id="party-size-rehearsal" class="form-group">
        <%= label_tag :party_rehearsal, 'How many people will be attending the Rehearsal dinner?', :class => 'control-label col-sm-4' %>
        <div class="col-sm-3">
            <%= text_field_tag :party_rehearsal, '', :class => 'form-control', :type => 'number', :min => 1 %>
        </div>
    </div>

    <div class="form-group brunch">
        <%= label_tag :brunch, 'Will <i>everyone</i> in your party be attending the <strong>Sunday brunch</strong> on <strong>Sunday, July 26</strong>?'.html_safe, :class => 'control-label col-sm-4' %>
        <div class="col-sm-3">
            <label class="radio-inline">
                <input type="radio" name="rsvp_brunch" id="yes-brunch" value='1'> Yes
            </label>
            <label class="radio-inline">
                <input type="radio" name="rsvp_brunch" id="no-brunch" value='0'> No
            </label>
        </div>
    </div>
    <div id="party-size-brunch" class="form-group">
        <%= label_tag :party_brunch, 'How many people will be attending the Sunday brunch?', :class => 'control-label col-sm-4' %>
        <div class="col-sm-3">
            <%= text_field_tag :party_brunch, '', :class => 'form-control', :type => 'number', :min => 1 %>
        </div>
    </div>

    <div id='details' class='hidden'>
        <h3 id='preferences'>Party Guests</h3>

        <div class="form-group meal-preference">
          <%= label_tag :meal, 'Meal Preference', :class => 'meal control-label col-sm-6' %>
          <div class="col-sm-6 hidden">
            <%= select_tag :meal, options_for_select(["Chicken", "Beef", "Child"], 'Chicken'), :include_blank => true, :class => 'form-control' %>
          </div>
        </div>
      </div>

      <button type="submit" class="btn btn-primary">RSVP</button>
  <% end %>

  <%= render 'home/footer' %>
</div>

<script>
    $(function () {
        setup_rsvp($('#party'), $('#details'), $('.meal-preference'), $('#preferences'));
    });
</script>

app/views/home/user_update.html.erb
<div class="info-box rsvp">
  <header>Update Address</header>

  <section>
    Please update your address so that we can send you an invitation.
  </section>

  <%= form_tag("/update_party", method: "get", :class => 'form-horizontal', :role => 'form') do |f| %>
      <% if @party.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@party.errors.count, "error") %> prohibited this party from being saved:</h2>

            <ul>
              <% @party.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

      <%= hidden_field_tag :id, @party.id %>

      <div class="form-group">
        <%= label_tag :address, 'Address', :class => 'col-sm-3 control-label' %>
        <div class="col-sm-9">
          <%= text_field_tag :address, @party.address, :class => 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <%= label_tag :city, 'City', :class => 'col-sm-3 control-label' %>
        <div class="col-sm-9">
          <%= text_field_tag :city, @party.city, :class => 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <%= label_tag :state, 'State', :class => 'col-sm-3 control-label' %>
        <div class="col-sm-9">
          <%= text_field_tag :state, @party.state, :class => 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <%= label_tag :postal_code, 'Postal Code', :class => 'col-sm-3 control-label' %>
        <div class="col-sm-9">
          <%= text_field_tag :postal_code, @party.postal_code, :class => 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <%= label_tag :country, 'Country', :class => 'col-sm-3 control-label' %>
        <div class="col-sm-9">
          <%= text_field_tag :country, @party.country, :class => 'form-control' %>
        </div>
      </div>

      <div class="actions">
        <%= submit_tag 'Update', :class => 'btn btn-primary' %>
      </div>
  <% end %>
</div>

app/views/home/wedding.html.erb
<% date = '2015-05-01'.to_date %>

<div class="info-box venue">
  <header>The Ceremony</header>

  <% if Date.today >= date || user_signed_in? %>
      <div>
        <%= image_tag 'ceremony_venue.jpg' %>
        <h1>Mt. Zion Baptist Church</h1>

        <h3> 228 Mount Zion Road, Huntsville, AL 35806</h3>
        <section>
          The service will be held at Mount Zion Baptist Church in Huntsville, Alabama at 4 pm on July 25, 2015.
          Please arrive by 3:45 pm.
        </section>

        <div class="link"><a class="view" href="//www.mzbc.net/" target="_blank"></a></div>

        <%= render 'footer' %>
      </div>
  <% else %>
      <%= render 'common/to_be_announced' %>
  <% end %>
</div>

app/views/home/wedding_party.html.erb
<div class="info-box">
  <header>Wedding Party</header>

  <section>
    <%= render 'home/wedding_party/bridesmaids' %>

    <%= render 'home/wedding_party/groomsmen' %>

    <div style="clear: both;"></div>
  </section>

  <%= render 'footer' %>
</div>