config/routes.rb
Rails.application.routes.draw do
  resources :tables

  devise_for :users, :skip => :registrations

  resources :parties
  resources :groups
  resources :guests
  resources :users

  get '/save-the-date-a' => 'parties#save_the_date_a'
  get '/save-the-date-b' => 'parties#save_the_date_b'
  get '/save-the-date-special' => 'parties#save_the_date_special'
  get '/reminder' => 'parties#send_reminder_email'
  get '/outer_labels' => 'parties#create_outer_labels'
  get '/place_cards' => 'parties#create_place_card_labels'
  get '/seating_chart' => 'parties#get_seating_chart_data'
  get '/rsvp_details' => 'parties#get_party_details'
  get '/tags' => 'parties#tags'
  get '/rsvp_cards' => 'parties#rsvp_cards'
  get '/detail' => 'parties#detail_list'

  root 'home#index'

  get '/our_story' => 'home#our_story'
  get '/wedding' => 'home#wedding'
  get '/reception' => 'home#reception'
  get '/registry' => 'home#registry'
  get '/wedding_party' => 'home#wedding_party'
  get '/guest_info' => 'home#guest_info'
  get '/rsvp' => 'home#rsvp'
  get '/pictures' => 'home#photos'

  get '/rsvp/search' => 'home#search'
  get '/address_update' => 'home#user_update'
  get '/update_party' => 'home#update_party'
  get '/party_guests/:id' => 'home#get_guests'
  get '/get_parties/:id' => 'home#get_parties'

  resources :photos

end

app/views/common/_guest_summary.html.erb
<p class='visible-xs visible-sm' id="notice"><%= notice %></p>
<br>

<table class="table table-bordered table-responsive">
  <thead>
  <tr>
    <th></th>
    <th>Guests</th>
    <th>Invitations</th>
    <th>Men</th>
    <th>Women</th>
    <th>Children</th>
    <th>Bride's Family</th>
    <th>Bride's Friends</th>
    <th>Groom's Family</th>
    <th>Groom's Friends</th>
  </tr>
  </thead>

  <tbody>
  <tr>
    <th>A Group</th>
    <%= guest_data 'A' %>
  </tr>

  <tr>
    <th>B Group</th>
    <%= guest_data 'B' %>
  </tr>
  </tbody>

  <thead>
  <tr>
    <th>Total</th>
    <th><%= Guest.all.count %></th>
    <th><%= Party.all.count %></th>
    <th><%= Guest.where(gender: 'Male', child: false).count %></th>
    <th><%= Guest.where(gender: 'Female', child: false).count %></th>
    <th><%= Guest.where(child: true).count %></th>
    <th><%= GroupsGuests.where(group_id: 1).count %></th>
    <th><%= GroupsGuests.where(group_id: 2).count %></th>
    <th><%= GroupsGuests.where(group_id: 3).count %></th>
    <th><%= GroupsGuests.where(group_id: 4).count %></th>
  </tr>
  </thead>

</table>

<p>
  <strong>Attending:</strong> <%= Party.where(rsvp: true).sum(:size) %> |
  <strong>Not Attending:</strong> <%= Party.where(rsvp: false).sum(:size) %>
</p>

<p>
  <strong>Missing Email Addresses:</strong> <%= Party.where("email IS NULL OR email = ''").count %> |
  <strong>Missing Addresses:</strong> <%= Party.where("address IS NULL OR address = ''").count %>
</p>

<%= link_to 'Download Labels', outer_labels_path(:format => :csv), :class => 'btn btn-success white-text' %>
<%= link_to 'Download Place Card Labels', place_cards_path(:format => :csv), :class => 'btn btn-success white-text' %>
<%= link_to 'Download Seating Chart Data', seating_chart_path(:format => :csv, :list => 'A'), :class => 'btn btn-success white-text' %>
<%= link_to 'Download A List', seating_chart_path(:format => :csv, :list => 'A'), :class => 'btn btn-success white-text' %>
<%= link_to 'Download B List', seating_chart_path(:format => :csv, :list => 'B'), :class => 'btn btn-success white-text' %>

<br>

app/views/common/_modal.html.erb
<div class="modal fade" id="selected-record" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">
          <span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel"></h4>
      </div>
      <div class="modal-body">

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/common/_to_be_announced.html.erb
<div class="to-be-announced">
  <h1>To Be Announced</h1>
</div>